todays-yum-yum/yum-yum

yum-yum/package.json, yum-yum/src/main.jsx
- 캐싱 작업을 위한 React-Query 라이브러리 추가
- 
- package에 라이브러리가 추가
- main.jsx에 QueryClient 인스턴스 생성
- 
-
=> [core] React Query 추가

yum-yum/src/components/EmptyState.jsx
- 빈 값을 나타내는 EmptyState 컴포넌트 추가
- children 안 쓸 경우 기본 값 Not Found
- 높이의 경우 임의로 h-[calc(100vh-180px)]로 설정(추후 수정 필요)
- <EmptyState /> 기본 값 "Not Found"
- <EmptyState>검색 결과가 없습니다.</EmptyState>
=> [feat] EmptyState 컴포넌트 추가

yum-yum/src/components/BottomBar.jsx, yum-yum/src/components/Header.jsx
- 바텀바 url 동기화 및 hidden 추가
- url로 들어가도 해당 메뉴 활성화
- 조건으로 바텀바 숨김 처리
```jsx
// 바텀바 숨기고 싶은 페이지 추가
const BottomHiddenPage = ['/meal', '/water'];
// 바텀바 없는 페이지
const isBottomHiddenPage = BottomHiddenPage.some((page) => location.pathname.startsWith(page)); 
```
=> [refactor] bottombar url 동기화 및 hidden 추가

yum-yum/src/components/common/Input.jsx, yum-yum/src/pages/report/ReportPage.jsx, yum-yum/src/styles/index.css
- Input 공통 컴포넌트
- Input 컴포넌트 추가
- Input컴포넌트를 Import 하여 사용.
- 각종 props를 전달하면서 기능 작동여부 확인
> 라벨링이 필요하면 요청해주세요.
=> [Feat] input 컴포넌트 추가

yum-yum/src/components/Modal.jsx
- 모달 컴포넌트 추가
- `modal.jsx`추가
```jsx
<Modal
isOpenModal={openModal}
onCloseModal={() => setOpenModal(false)}
title='수분 섭취량 설정'
showClose={true}  // 닫기 버튼 활성화
btnLabel='확인'
onBtnClick={handleModifyIntake}
btnDisabled={true}  // 버튼 비활성화
>
<p>children 영역</p>
</Modal>
```
=> [feat] modal 컴포넌트 추가

yum-yum/src/data/mockUser.js
- 원활한 개발을 위한 테스트용 사용자 목업 데이터
- 실 데이터 처럼 유저데이터 생성
```
// /data/mockUser.js
// 테스트용 유저데이터
const mockUser = {
_id: '1',
userId: 'test@gmail.com',
name: '김철수',
password: 'password123', // 테스트용(암호화xx)
profileImage: null, // 이미지 따로 저장하고 여긴 url만 저장 - 마이페이지 개발 시 사용
gender: 'male',
age: 28,
weight: 75,
height: 175,
goals: {
targetWeight: 70,
targetExercise: 'moderate', // ['none', 'light', 'moderate', 'intense']
},
createdAt: new Date('2025-09-01T10:00:00.000Z'),
updatedAt: new Date('2025-09-01T10:00:00.000Z'),
};
```
=> [feat] 사용자 목업 데이터 생성

yum-yum/src/components/common/Input.jsx, yum-yum/src/pages/meal/component/NutritionSection.jsx, yum-yum/src/pages/meal/page/CustomEntryForm.jsx, yum-yum/src/services/customFoodsApi.js, yum-yum/src/services/firebase.js, yum-yum/src/stores/useCustomFoodStore.js, yum-yum/src/styles/index.css, yum-yum/src/utils/NutrientNumber.js
- input number 기본 화살표 제거
- input number 기본 화살표 제거
=> [style] input number 화살표 제거

yum-yum/src/assets/icons/icon-close.svg, yum-yum/src/components/Modal.jsx
- 모달 컴포넌트 수정
- icon-close 파일 교체 (아이콘이 바뀌어 있어서 너비, 높이 설정 안하면 안보이는 문제 발생)
- 아이콘 너비, 높이 설정 삭제
- 간격 수정
=> [refator] modal 컴포넌트 닫기 아이콘 수정 및 간격 수정

yum-yum/src/pages/meal/component/TotalBarChart.jsx, yum-yum/src/pages/meal/page/TotalMeal.jsx
- 식단 기록 상세페이지 차트 ui 추가
- 바 차트 추가
=> [feat] 식단 기록 상세페이지 차트 ui 추가

yum-yum/src/pages/water/WaterPage.jsx, yum-yum/src/pages/water/component/WaterIntakeModal.jsx
- 수분 기록 페이지 ui
- water-page ui
- 수분 섭취량 모달 ui
=> [feat] water-page ui

yum-yum/src/pages/home/HomePage.jsx, yum-yum/src/pages/home/card/calorie/CalorieNutrition.jsx, yum-yum/src/pages/home/card/weight/WeightCard.jsx, yum-yum/src/utils/mainDataParser.js
- 음식데이터가 여러개인경우 호출 시 에러 발생
- 음식 파싱하는 로직 수정
- 탄단지, 몸무게 소수점 첫째자리 표출
- localhost:5173 접속 후, 날짜를 09월 13일 선택
- 이슈 없이 화면이 잘 나오는지 확인
=> [fix] 음식데이터가 여러개인경우 호출 시 에러 수정

yum-yum/src/App.jsx, yum-yum/src/hooks/useNutritionAnalysis.js, yum-yum/src/pages/home/card/nutrition/MealCard.jsx, yum-yum/src/pages/home/card/weight/WeightCard.jsx, yum-yum/src/pages/meal/MealPage.jsx, yum-yum/src/pages/meal/page/FoodSearchResults.jsx, yum-yum/src/services/nutritionAnalysis.js, yum-yum/src/services/searchFoodApi.js, yum-yum/src/stores/useSearchFoodStore.js, yum-yum/src/utils/mainDataParser.js
- 메인화면 소수점 처리가 안되어있음
- [아침, 점심, 저녁, 기타]별로 칼로리를 표출하는 부분에 칼로리 표출이 되고 있지 않음
- `MealCard` : 섭취한 수분은 소수점 첫째자리까지 표출, 칼로리는 반올림하여 표출
- `parseMealsByType(meals)` : mealType별 데이터 파싱할 때, 칼로리 호출이 잘 못 되어있어 수정
- `meal.kcal` → `meal.nutrient.kcal` 수정 
- `WeightCard` : 몸무게 계산 부분 소수점 첫째자리까지 표출
-
=> [fix] 메인화면 소수점 처리, 칼로리 표출 이슈수정

yum-yum/src/pages/auth/LoginPage.jsx, yum-yum/src/styles/index.css
- 로그인 페이지 화면 배치
- `LoginPage.jsx` 화면 배치
- 회원가입 버튼 클릭시, `/signup` 페이지 이동
- `useAuth`에서 `isAuthenticated` 값을 `false`로 지정
=> [fix] 로그인 페이지 UI 배치

yum-yum/src/services/searchFoodApi.js
- 음식 리스트 업체명 없으면 제조사명 나오도록 해당없음일 경우 빈값으로 나오도록 추가
```jsx
makerName:
item.companyNm && item.companyNm !== '해당없음'
? item.companyNm
: item.mkrNm && item.mkrNm !== '해당없음'
? item.mkrNm
: '',
```
=> [fix] 음식 리스트 업체명 없으면 제조사명 나오도록 해당없음일 경우 빈값으로 나오도록 추가

yum-yum/src/hooks/useMainPageData.js, yum-yum/src/hooks/useUser.js, yum-yum/src/main.jsx, yum-yum/src/pages/home/HomePage.jsx, yum-yum/src/services/firebase.js
- 한 개의 함수에서 두개의 react-query를 호출하고 있어 재사용성이 떨어짐
- useMainPageData → useUser(유저 데이터) 분리
- 
-
=> [Refactor] 리엑트 쿼리 함수 분리

yum-yum/src/hooks/useReportData.js, yum-yum/src/pages/report/charts/LineCharts.jsx, yum-yum/src/pages/report/components/WaterWeightInfo.jsx, yum-yum/src/pages/report/pages/DietReportPage.jsx, yum-yum/src/pages/report/pages/WaterReportPage.jsx, yum-yum/src/utils/dateUtils.js, yum-yum/src/utils/reportDataParser.js
- 수분 리포트 데이터 연동
- 수분 데이터 가공 
- 수분 데이터 차트 표기 및 상세 정보 제공
- 수분 리포트 날짜 변경 및 단위 기간 변경시 데이터가 모두 나오는지 확인
> 테스트 중 특히 단위 기간 변경 시 오류가 발생하지 않는지 봐주세요.
=> [Feat] 수분 리포트 데이터 연동

yum-yum/src/services/weightApi.js
- 몸무게 변화를 기록하기 위한 로그 기록
- `weightApi`에서 weight 문서에 저장하는 코드 추가
- `batch`를 사용하여 users 문서와 weight 문서에서 저장하는 도중 에러가 났을 때, 두가지 다 롤백이 되도록 설정
- 홈 화면에서 체중 입력 후, firestore에 weight 문서내부에 데이터가 추가되었는지 확인
- 혹은 리포트의 체중 확인(리포트의 체중 페이지가 완성되어있는경우)
=> [feat] 몸무게 로그 기록

yum-yum/src/components/common/OnBoarding.jsx, yum-yum/src/components/modal/MenuModal.jsx
- 온보딩, 플로팅 버튼 식단추가 모달 호출 시 스크롤 막기
- 온보딩 호출 시 body 스크롤 막기
- 플로팅 버튼 내 식단 추가 모달 호출 시 body 스크롤 막기 및 사이즈 조정
=> [feat] 온보딩, 플로팅 버튼 식단추가 모달 호출 시 스크롤 막기

yum-yum/src/pages/report/pages/ReportPage.jsx
- 리포트 페이지 쿼리스트링 추가
- 리포트 각 분야별 탭에 쿼리스트링을 추가
- 리포트 페이지에서 각 분야별 탭 클릭하면서 쿼리스트링이 적용되는지 확인
=> [Feat] 리포트 페이지 쿼리스트링 추가

yum-yum/src/pages/meal/component/MealHeader.jsx
- 검색창 지우기 버튼 추가
- CloseIcon 추가
- CloseIcon 클릭 시 입력 값 초기화
- input에 값 입력 시 CloseIcon 버튼 활성화
- CloseIcon 클릭 시 입력 값 초기화
=> [feat] 검색창 지우기 버튼 추가

yum-yum/src/pages/report/components/ChartArea.jsx, yum-yum/src/pages/report/pages/AiReportPage.jsx, yum-yum/src/pages/report/pages/ReportPage.jsx, yum-yum/src/pages/report/pages/WeightReportPage.jsx, yum-yum/src/stores/useReportStore.js
- 체중 리포트 일간 데이터 설정 시 매개변수 누락 수정
- 체중 리포트 일간 데이터 설정 시 매개변수 누락 수정
- 리포트 공간 증가
=> [Fix] 체중 리포트 몸무게 설정 오류 해결

yum-yum/src/pages/meal/component/FoodDetailModal.jsx, yum-yum/src/pages/meal/component/NutritionSection.jsx, yum-yum/src/pages/meal/page/CustomEntryForm.jsx
- 음식 상세 모달 react-hook-form으로 변경
- 용량 변경 시 string으로 바뀌는 이슈 수정
- 용량 수정 시 최대 값 지정
- 최소 값 10으로 변경되는 이슈 수정
- 값 지웠을 때 기본 값 0으로 설정되는 이슈 수정
=> [fix] 음식 상세 모달 react-hook-form으로 변경

yum-yum/src/hooks/useReportData.js, yum-yum/src/pages/report/pages/WeightReportPage.jsx, yum-yum/src/services/dailyDataApi.js, yum-yum/src/services/monthlyDataApi.js, yum-yum/src/services/weeklyDataApi.js, yum-yum/src/stores/useHomeStore.js, yum-yum/src/stores/useReportStore.js, yum-yum/src/utils/dateUtils.js, yum-yum/src/utils/localStorage.js, yum-yum/src/utils/reportDataParser.js
- 체중 추이 표출
- 일간 무게 범위 설정 : 선택한 날짜 기준의 한 주의 데이터를 모두 가져와야 함
- 주간 무게 범위 설정 : 선택한 날짜 기준의 한 달의 데이터를 모두 가져와서 한 주당 마지막에 기록된 무게로 표현
- 월간 무게 범위 설정 : 선택한 날짜 기준의 일 년의 데이터를 가져와서 한 달의 마지막 데이터를 무게로 표현
- 각 주마다 체중 데이터 입력, 지난달 체중 데이터 입력 후, 리포트 이동 
- 1개 이상 입력
- Close #117
=> [fix] 체중 추이 표출

yum-yum/package.json, yum-yum/src/components/common/LoadingSpinner.jsx, yum-yum/src/hooks/useMeals.js, yum-yum/src/hooks/useNutritionAnalysis.js, yum-yum/src/pages/meal/component/NutritionSection.jsx, yum-yum/src/pages/report/charts/LineCharts.jsx, yum-yum/src/pages/report/charts/StackedCharts.jsx, yum-yum/src/pages/report/components/ChartArea.jsx, yum-yum/src/pages/report/pages/AiReportPage.jsx, yum-yum/src/pages/report/pages/DietReportPage.jsx, yum-yum/src/pages/report/pages/ReportPage.jsx, yum-yum/src/services/nutritionAnalysis.js
- 차트가 화면을 넘어가는 현상 수정, 로딩 스피너 추가
- 라인 차트가 모바일 환경에서 화면을 넘어가는 현상 수정
- 로딩 스피너 추가
- AI 리포트 배경 길이 수정
- AI 리포트 결과 1차 수정
- AI 리포트에서 스피너가 보이는지 확인
- AI 리포트 배경(primary-light)이 전부를 차지하는지 확인
=> [Fix] 반응형 오류 해결

yum-yum/src/services/weightApi.js
- 오타 수정
- 파이어베이스 저장할 때 사용하는 ref 변수명 오타 수정
- 오타 수정전에 저장이 되지 않았는데, 수정이후 정상적으로 저장
=> [fix] weightapi에서 오타 수정
